---
- name: Prepare SSH and install NGINX
  hosts: all
  become: true
  tasks:
    - name: Add hosts to known_hosts
      shell: |
        ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
      delegate_to: localhost
      ignore_errors: yes

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present
